imports:
    - { resource: "services/extractor.yml" }

services:
    _defaults:
        public: true

    coreshop.registry.seo.extractor:
        class: CoreShop\Component\Registry\ServiceRegistry
        arguments:
            - 'CoreShop\Component\SEO\Extractor\ExtractorInterface'
            - 'seo metadata extractor'

    CoreShop\Component\SEO\SEOPresentation:
        arguments:
            - '@Pimcore\Templating\Helper\HeadMeta'
            - '@Pimcore\Templating\Helper\HeadTitle'
            - '@coreshop.registry.seo.extractor'

    coreshop.seo.presentation: '@CoreShop\Component\SEO\SEOPresentation'
    CoreShop\Component\SEO\SEOPresentationInterface: '@CoreShop\Component\SEO\SEOPresentation'
