services:
    _defaults:
        public: true

    coreshop.seo.extractor.lucene_search: '@CoreShop\Component\SEO\Extractor\LuceneSearchExtractor'
    CoreShop\Component\SEO\Extractor\LuceneSearchExtractor:
        arguments:
            - '@LuceneSearchBundle\Tool\CrawlerState'
        tags:
            - { name: coreshop.seo.extractor, type: lucene_search }
